### ISSUE TITLE
ToDo

### ISSUE THREAD

**Issue by yammerjp** [basd4g/gimonfu#2]
- [x] download all articles
- [x] post an article
- [x] put an article
- [x] compare local article's date with the remote article's one
- [x] update posted/put article
- [x] pull
- [x] push
- [ ] sync
- [x] commit date option

**Comment by yammerjp** [comment]
git log --pretty=format:'%cd' --date=iso -- path/to/file/or/dir | head -n 1

特定ファイルの最新コミット日時を取得
